/** Plain-English definitions surfaced on hover for potentially-confusing terms. */
export const GLOSSARY: Record<string, string> = {
  ADD: "Buy more of a position you already own.",
  TRIM: "Sell part of a position to reduce risk or lock gains.",
  HOLD: "Keep the position as-is; thesis intact and fairly valued.",
  SELL: "Exit the position fully; thesis broken or better uses of capital.",
  BUY: "Open a new position at today's price.",
  WATCH: "Not yet — wait for a specific trigger before acting.",
  PASS: "Not compelling right now; skip it.",
  conviction: "The model's calibrated probability the call is right (0–100%), not certainty.",
  invalidation: "What would prove the thesis wrong — the exit/avoid condition.",
  rMultiple: "Reward-to-risk: expected gain to target divided by loss to stop.",
  expectedReturnPct: "Expected % move to the target over the stated horizon.",
  trigger: "The specific, testable condition that turns a WATCH into action.",
  rsi14: "Relative Strength Index (14d): >70 overbought, <30 oversold.",
  macd: "MACD: trend-momentum; positive = bullish momentum.",
  atr14: "Average True Range (14d): typical daily price movement (volatility).",
  bbPercentB: "Bollinger %B: position within the bands; >1 above upper, <0 below lower.",
  peTrailing: "Price / trailing 12-month earnings — valuation multiple.",
  peg: "P/E divided by growth — valuation adjusted for growth.",
  evEbitda: "Enterprise value / EBITDA — capital-structure-neutral valuation.",
  roe: "Return on equity — profit generated on shareholders' capital.",
  freeCashFlowPerShare: "Free cash flow per share — cash the business throws off.",
};
